services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/dogpics
    depends_on:
      - mongo
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm start 

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
